name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nodenv/actions/node-version@main
        id: nodenv
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'
      - run: node -v
